### ISSUE TITLE
Generating ground truth transformation 

### ISSUE THREAD

**Issue by NahomKidane** [hummat/easy-o3d#5]
Hi 

First off, very useful and excellent wrapper! I am currently using it to evaluate different pipeline setups and registration parameters. I just started looking at the code, but I had a question about getting ground truth transformation. What would be the best way to generate ground truth transformations? I already have some 3d scan data; should I randomly translate the data and save the change as a .json file? 

I also have the MPI FAUST Dataset (http://faust.is.tue.mpg.de/), which contains high-resolution human scans with automatically computed ground-truth correspondences. The ground truth is determined by aligning each scan with a standard template mesh ( a low-resolution template mesh with a resolution of 6890 vertices, which is included ). Can one use the ground data? 

Thank you!

**Comment by hummat** [comment]
Hi @NahomKidane, thanks, glad that it's useful. Yes, I think if you simply want to find the right parameters for your problem, randomly rotating/translating and saving the generated poses would be most straight forward.

I've generated the [test data](https://github.com/hummat/easy-o3d/tree/master/tests/test_data) used in the [tutorial](https://github.com/hummat/easy-o3d/blob/master/tutorial.ipynb) using [BlenderProc](https://github.com/DLR-RM/BlenderProc), which saves the data in the [BOP](https://github.com/thodan/bop_toolkit/blob/master/docs/bop_datasets_format.md) format for which there is a [reader](https://github.com/hummat/easy-o3d/blob/ee56dcd290adf577cb41c28bd191b3ac29baaa64/easy_o3d/utils.py#L810) implemented. This might be interesting to you if you have object meshes (like in the FAUST case).
